from __future__ import annotations

import hashlib
import re
from html import unescape
from urllib.parse import parse_qs, urljoin, urlparse

TITLE_RE = re.compile(r"<title[^>]*>(.*?)</title>", re.IGNORECASE | re.DOTALL)
FORM_RE = re.compile(r"<form\b", re.IGNORECASE)
INPUT_NAME_RE = re.compile(r"<input[^>]*\bname=['\"]?([A-Za-z0-9_\-:\[\]\.]+)", re.IGNORECASE)
WP_VERSION_RE = re.compile(r"wp-(?:content|includes).{0,80}?ver=([0-9][0-9A-Za-z\.\-_]+)", re.IGNORECASE)
PASSWORD_RE = re.compile(r"type=['\"]?password['\"]?", re.IGNORECASE)
SCRIPT_SRC_RE = re.compile(r"""<script[^>]*\bsrc=['"]([^'"]+)['"]""", re.IGNORECASE)
VERSION_RE = re.compile(r"([0-9]+(?:\.[0-9A-Za-z\-_]+){1,4})")
XML_LOC_RE = re.compile(r"<loc>\s*([^<]+)\s*</loc>", re.IGNORECASE)

LOGIN_TOKENS = (
    "login",
    "log in",
    "sign in",
    "sso",
    "single sign-on",
    "authenticate",
    "username",
    "password",
    "okta",
    "saml",
    "oauth",
    "citrix",
    "rdweb",
    "vpn",
)
ADMIN_TOKENS = (
    "/admin",
    "/administrator",
    "/manage",
    "/console",
    "/cpanel",
    "/wp-admin",
    "/portal",
    "admin panel",
    "management console",
    "control panel",
    "dashboard",
)
DEFAULT_PAGE_TOKENS = (
    "apache2 ubuntu default page",
    "nginx welcome",
    "welcome to nginx",
    "iis windows server",
    "it works!",
    "placeholder",
    "coming soon",
    "under construction",
    "default web site",
)
WAF_HEADER_TOKENS: dict[str, tuple[str, ...]] = {
    "cloudflare": ("cloudflare", "__cf_bm", "cf-ray", "cf-cache-status"),
    "akamai": ("akamai", "akamaighost", "x-akamai"),
    "imperva": ("imperva", "incap_ses", "x-cdn", "_incapsula"),
    "fastly": ("fastly", "x-served-by", "x-cache-hits"),
    "sucuri": ("sucuri", "x-sucuri-id", "x-sucuri-cache"),
    "cloudfront": ("cloudfront", "x-amz-cf-id", "x-cache"),
}
GENERIC_403_TOKENS = (
    "access denied",
    "request blocked",
    "forbidden",
    "attention required",
    "security check",
    "akamai",
    "cloudflare",
    "cloudfront",
    "incapsula",
    "imperva",
)
GENERIC_200_TOKENS = (
    "coming soon",
    "under construction",
    "placeholder",
    "default web site",
    "holding page",
)
PARKING_PAGE_TOKENS = {
    "cloudfront": ("generated by cloudfront", "bad request", "request could not be satisfied"),
    "azure": ("your azure function app is up and running", "azure front door", "app service"),
    "fastly": ("fastly error", "unknown domain"),
    "akamai": ("akamaighost", "reference #", "access denied"),
    "cloudflare": ("attention required", "ray id", "cloudflare"),
}
APPLIANCE_MARKERS = {
    "Citrix Gateway": ("citrix gateway", "netscaler gateway"),
    "Fortinet": ("fortinet", "fortigate", "fortigate firewall"),
    "Pulse Secure": ("pulse secure", "connect secure"),
    "F5 BIG-IP": ("big-ip", "f5 networks", "bigip"),
    "SonicWall": ("sonicwall",),
}
STORAGE_SUFFIXES = {
    "amazonaws.com": "aws",
    "storage.googleapis.com": "gcp",
    "blob.core.windows.net": "azure",
    "digitaloceanspaces.com": "digitalocean",
}


def extract_title(html_body: str) -> str | None:
    match = TITLE_RE.search(html_body)
    if not match:
        return None
    return unescape(match.group(1)).strip()[:300]


def count_forms(html_body: str) -> int:
    return len(FORM_RE.findall(html_body))


def extract_input_parameters(html_body: str, page_url: str) -> list[str]:
    names = {item.strip() for item in INPUT_NAME_RE.findall(html_body) if item and item.strip()}
    parsed = urlparse(page_url)
    for key in parse_qs(parsed.query).keys():
        if key.strip():
            names.add(key.strip())
    return sorted(names)


def detect_wordpress(html_body: str, headers: dict[str, str]) -> tuple[bool, str | None]:
    lowered = html_body.lower()
    if "wp-content" not in lowered and "wordpress" not in lowered:
        return False, None
    version_match = WP_VERSION_RE.search(html_body)
    version = version_match.group(1) if version_match else None
    if not version:
        generator = headers.get("x-generator", "")
        if "wordpress" in generator.lower():
            parts = generator.split()
            if len(parts) > 1:
                version = parts[-1]
    return True, version


def detect_technologies(headers: dict[str, str], html_body: str) -> list[tuple[str, str | None, float]]:
    technologies: list[tuple[str, str | None, float]] = []
    server = headers.get("server")
    if server:
        technologies.append(("Web Server", server, 0.7))
        lowered = server.lower()
        if "nginx" in lowered:
            technologies.append(("Nginx", server, 0.9))
        if "apache" in lowered:
            technologies.append(("Apache HTTP Server", server, 0.9))
        if "iis" in lowered:
            technologies.append(("Microsoft IIS", server, 0.9))

    powered_by = headers.get("x-powered-by")
    if powered_by:
        technologies.append(("X-Powered-By", powered_by, 0.7))
        lowered = powered_by.lower()
        if "php" in lowered:
            technologies.append(("PHP", powered_by, 0.9))
        if "asp.net" in lowered:
            technologies.append(("ASP.NET", powered_by, 0.9))
        if "express" in lowered:
            technologies.append(("Express", powered_by, 0.8))

    if "cloudflare" in headers.get("server", "").lower():
        technologies.append(("Cloudflare", None, 0.85))

    wp_detected, wp_version = detect_wordpress(html_body, headers)
    if wp_detected:
        technologies.append(("WordPress", wp_version, 0.95))

    lowered_body = html_body.lower()
    if "drupal-settings-json" in lowered_body or "sites/default/files" in lowered_body:
        technologies.append(("Drupal", None, 0.9))
    if "joomla!" in lowered_body or "/media/system/js/" in lowered_body:
        technologies.append(("Joomla", None, 0.85))
    if "_next/static" in lowered_body:
        technologies.append(("Next.js", None, 0.88))
    if "laravel" in lowered_body or "csrf-token" in lowered_body:
        technologies.append(("Laravel", None, 0.78))
    if "react" in lowered_body:
        technologies.append(("React", None, 0.65))
    for appliance_name, tokens in APPLIANCE_MARKERS.items():
        if any(token in lowered_body for token in tokens):
            version = _extract_nearby_version(lowered_body, tokens)
            technologies.append((appliance_name, version, 0.93 if version else 0.88))

    return technologies


def _extract_nearby_version(text: str, tokens: tuple[str, ...]) -> str | None:
    for token in tokens:
        index = text.find(token)
        if index < 0:
            continue
        window = text[max(0, index - 60) : index + 120]
        match = VERSION_RE.search(window)
        if match:
            return match.group(1)
    return None


def _normalize_body_tokens(value: str) -> str:
    return re.sub(r"\s+", " ", re.sub(r"[0-9a-f]{8,}", "", value.lower())).strip()


def detect_login_portal(
    html_body: str,
    headers: dict[str, str],
    page_url: str,
    title: str | None,
    input_parameters: list[str],
) -> tuple[bool, list[str]]:
    lowered = " ".join(
        [
            html_body.lower(),
            (title or "").lower(),
            page_url.lower(),
            " ".join(item.lower() for item in input_parameters),
            headers.get("www-authenticate", "").lower(),
        ]
    )
    reasons: list[str] = []
    if PASSWORD_RE.search(html_body):
        reasons.append("password input field detected")
    if any(token in lowered for token in LOGIN_TOKENS):
        reasons.append("login-oriented terms detected")
    if {"username", "email", "user", "login"} & {item.lower() for item in input_parameters}:
        reasons.append("credential-style input names detected")
    return bool(reasons), reasons


def detect_admin_interface(html_body: str, page_url: str, title: str | None) -> tuple[bool, list[str]]:
    lowered = " ".join([html_body.lower(), page_url.lower(), (title or "").lower()])
    reasons = [token for token in ADMIN_TOKENS if token in lowered]
    return bool(reasons), reasons[:4]


def detect_default_page(html_body: str, title: str | None, headers: dict[str, str]) -> tuple[bool, list[str]]:
    lowered = " ".join([html_body.lower(), (title or "").lower(), headers.get("server", "").lower()])
    reasons = [token for token in DEFAULT_PAGE_TOKENS if token in lowered]
    return bool(reasons), reasons[:4]


def detect_waf_cdn(headers: dict[str, str]) -> tuple[str | None, float]:
    flattened = " ".join([f"{key}:{value}".lower() for key, value in headers.items()])
    for provider, tokens in WAF_HEADER_TOKENS.items():
        matched = [token for token in tokens if token in flattened]
        if matched:
            return provider, min(0.98, 0.55 + (0.1 * len(matched)))
    return None, 0.0


def normalized_body_fingerprint(html_body: str) -> str:
    lowered = _normalize_body_tokens(html_body)
    return lowered[:400]


def detect_soft_404(
    primary_status: int | None,
    primary_body: str,
    random_status: int | None,
    random_body: str,
) -> bool:
    if random_status == 404:
        return False
    if primary_status is None or random_status is None:
        return False
    if random_status >= 500:
        return False
    primary_fp = normalized_body_fingerprint(primary_body)
    random_fp = normalized_body_fingerprint(random_body)
    if not primary_fp or not random_fp:
        return False
    if primary_fp == random_fp:
        return True
    overlap = len(set(primary_fp.split()) & set(random_fp.split()))
    return overlap >= 12 and abs(len(primary_fp) - len(random_fp)) <= 80


def favicon_hash(icon_bytes: bytes) -> str | None:
    if not icon_bytes:
        return None
    return hashlib.sha1(icon_bytes).hexdigest()  # noqa: S324


def extract_script_urls(base_url: str, html_body: str, same_host_only: bool = True) -> list[str]:
    scripts: list[str] = []
    base_host = (urlparse(base_url).hostname or "").lower()
    for match in SCRIPT_SRC_RE.finditer(html_body or ""):
        raw = (match.group(1) or "").strip()
        if not raw:
            continue
        candidate = urljoin(base_url, raw)
        parsed = urlparse(candidate)
        if parsed.scheme not in {"http", "https"}:
            continue
        host = (parsed.hostname or "").lower()
        if same_host_only and base_host and host and host != base_host:
            continue
        if candidate not in scripts:
            scripts.append(candidate)
    return scripts


def detect_redirect_loop(redirect_chain: list[dict[str, object]], final_url: str | None = None) -> tuple[bool, list[str]]:
    if not redirect_chain:
        return False, []
    seen: set[str] = set()
    reasons: list[str] = []
    for item in redirect_chain:
        source = str(item.get("from") or "")
        destination = str(item.get("to") or "")
        if destination in seen:
            reasons.append(f"redirect repeated destination {destination}")
            break
        if source == destination and source:
            reasons.append(f"self-redirect detected for {source}")
            break
        seen.add(source)
        seen.add(destination)
    if final_url and final_url in {str(item.get("from") or "") for item in redirect_chain}:
        reasons.append("final URL was previously seen in redirect chain")
    if len(redirect_chain) >= 4:
        reasons.append("long redirect chain may mask the real application")
    return bool(reasons), reasons[:4]


def detect_generic_http_response(
    primary_status: int | None,
    primary_body: str,
    primary_title: str | None,
    canary_responses: list[dict[str, object]],
) -> dict[str, object] | None:
    if primary_status not in {200, 403}:
        return None
    primary_fp = normalized_body_fingerprint(primary_body)
    if not primary_fp:
        return None
    matched: list[dict[str, object]] = []
    for canary in canary_responses:
        canary_status = canary.get("status_code")
        canary_body = str(canary.get("body_text") or "")
        if canary_status != primary_status:
            continue
        canary_fp = normalized_body_fingerprint(canary_body)
        if not canary_fp:
            continue
        if primary_fp == canary_fp:
            matched.append(canary)
            continue
        overlap = len(set(primary_fp.split()) & set(canary_fp.split()))
        if overlap >= 10 and abs(len(primary_fp) - len(canary_fp)) <= 120:
            matched.append(canary)
    if not matched:
        return None
    lowered = " ".join([primary_fp, (primary_title or "").lower()])
    reasons = [f"{len(matched)} canary responses closely matched the primary response"]
    if primary_status == 403 and any(token in lowered for token in GENERIC_403_TOKENS):
        reasons.append("403 response contains generic block-page markers")
    if primary_status == 200 and any(token in lowered for token in GENERIC_200_TOKENS):
        reasons.append("200 response looks like a generic placeholder or parking page")
    confidence = min(0.97, 0.6 + (0.12 * len(matched)))
    trust_score = max(0.15, 0.55 - (0.12 * len(matched)))
    return {
        "status_code": primary_status,
        "trust_score": round(trust_score, 2),
        "confidence": round(confidence, 2),
        "reasons": reasons,
        "matched_canaries": len(matched),
    }


def detect_cdn_parking_page(
    headers: dict[str, str],
    title: str | None,
    body_text: str,
    page_url: str,
) -> tuple[str | None, list[str]]:
    combined = " ".join(
        [
            " ".join(f"{key}:{value}".lower() for key, value in headers.items()),
            (title or "").lower(),
            _normalize_body_tokens(body_text)[:600],
            page_url.lower(),
        ]
    )
    for provider, tokens in PARKING_PAGE_TOKENS.items():
        reasons = [token for token in tokens if token in combined]
        if reasons:
            return provider, reasons[:4]
    return None, []


def assess_response_trust(
    generic_response: dict[str, object] | None,
    redirect_loop: bool,
    parking_provider: str | None,
    waf_provider: str | None,
) -> tuple[float, list[str]]:
    trust = 0.9
    reasons: list[str] = []
    if generic_response:
        trust = min(trust, float(generic_response.get("trust_score", 0.4)))
        reasons.extend(str(item) for item in generic_response.get("reasons", []))
    if redirect_loop:
        trust = min(trust, 0.45)
        reasons.append("redirect behavior may be hiding the true application response")
    if parking_provider:
        trust = min(trust, 0.35)
        reasons.append(f"{parking_provider} parking/default response detected")
    if waf_provider and not generic_response:
        trust = min(trust, 0.65)
        reasons.append(f"{waf_provider} may be filtering or normalizing responses")
    return round(trust, 2), reasons[:6]


def explain_technology_fingerprints(headers: dict[str, str], html_body: str) -> list[dict[str, object]]:
    lowered_body = html_body.lower()
    rows: list[dict[str, object]] = []
    for name, version, confidence in detect_technologies(headers, html_body):
        lowered_name = name.lower()
        sources: list[str] = []
        version_sources: list[str] = []
        if lowered_name in {"web server", "nginx", "apache http server", "microsoft iis", "cloudflare"}:
            if headers.get("server"):
                sources.append("header")
                if version and VERSION_RE.search(headers.get("server", "")):
                    version_sources.append("header")
        elif lowered_name in {"x-powered-by", "php", "asp.net", "express"}:
            if headers.get("x-powered-by"):
                sources.append("header")
                if version and VERSION_RE.search(headers.get("x-powered-by", "")):
                    version_sources.append("header")
        elif lowered_name == "wordpress":
            if "wp-content" in lowered_body or "wordpress" in lowered_body:
                sources.append("body")
            if "x-generator" in headers and "wordpress" in headers.get("x-generator", "").lower():
                sources.append("header")
                if version:
                    version_sources.append("header")
            if version and "body" in sources:
                version_sources.append("body")
        else:
            if lowered_name and lowered_name.replace(".", "") in lowered_body.replace(".", ""):
                sources.append("body")
            if version:
                version_sources.append("body")
        unique_sources = sorted(set(sources)) or ["body"]
        unique_version_sources = sorted(set(version_sources))
        if len(unique_version_sources) >= 2:
            tier = "multi-source corroborated"
        elif any(name.startswith(prefix) for prefix in APPLIANCE_MARKERS):
            tier = "strong appliance fingerprint"
        elif unique_sources == ["header"] and version:
            tier = "header only"
        elif version and {"header", "body"} <= set(unique_sources):
            tier = "banner + body"
        elif version and unique_sources:
            tier = "banner + body" if "body" in unique_sources else "header only"
        else:
            tier = "body only"
        rows.append(
            {
                "name": name,
                "version": version,
                "confidence": round(float(confidence), 2),
                "sources": unique_sources,
                "version_confidence_tier": tier,
            }
        )
    return rows


def detect_cloud_storage_posture(
    page_url: str,
    headers: dict[str, str],
    body_text: str,
) -> dict[str, object] | None:
    parsed = urlparse(page_url)
    host = (parsed.hostname or "").lower()
    provider = None
    for suffix, provider_name in STORAGE_SUFFIXES.items():
        if host == suffix or host.endswith(f".{suffix}"):
            provider = provider_name
            break
    lowered_headers = " ".join(f"{key}:{value}".lower() for key, value in headers.items())
    lowered_body = _normalize_body_tokens(body_text)[:1200]
    if provider is None:
        if "x-amz-bucket-region" in lowered_headers or "x-amz-request-id" in lowered_headers:
            provider = "aws"
        elif "x-goog-storage-class" in lowered_headers or "googleapis" in lowered_headers:
            provider = "gcp"
        elif "x-ms-request-id" in lowered_headers or "x-ms-version" in lowered_headers:
            provider = "azure"
    if provider is None:
        return None
    query = parse_qs(parsed.query)
    object_listing = any(
        marker in lowered_body
        for marker in ("listbucketresult", "<contents>", "<blob>", "<enumerationresults>", "<key>")
    )
    static_site = any(
        marker in lowered_body or marker in lowered_headers
        for marker in ("static website hosting", "amazon s3", "x-amz-website", "azure static web apps")
    )
    signed_url = any(
        key.lower() in {"x-amz-signature", "x-amz-credential", "googleaccessid", "signature", "expires", "sv", "sp", "sig", "se"}
        for key in query
    )
    bucket_name = host.split(".", 1)[0] if "." in host else host
    source_host = ""
    if parsed.netloc:
        source_host = parsed.netloc.split(":")[0].lower()
    naming_reuse = bool(bucket_name and source_host and bucket_name in source_host)
    reasons = [f"{provider} storage-like endpoint detected"]
    if object_listing:
        reasons.append("object listing markers detected")
    if static_site:
        reasons.append("static hosting markers detected")
    if signed_url:
        reasons.append("signed URL markers detected")
    if naming_reuse:
        reasons.append("bucket/container name appears tied to target naming")
    return {
        "provider": provider,
        "object_listing": object_listing,
        "static_site": static_site,
        "signed_url": signed_url,
        "bucket_name": bucket_name,
        "naming_reuse": naming_reuse,
        "reasons": reasons,
    }


def extract_structured_urls(base_url: str, body_text: str, same_host_only: bool = True) -> list[str]:
    structured: list[str] = []
    base_host = (urlparse(base_url).hostname or "").lower()
    candidates = []
    candidates.extend(XML_LOC_RE.findall(body_text or ""))
    candidates.extend(re.findall(r"(?im)^(?:allow|disallow|sitemap):\s*(\S+)$", body_text or ""))
    for candidate in candidates:
        absolute = urljoin(base_url, candidate.strip())
        parsed = urlparse(absolute)
        if parsed.scheme not in {"http", "https"}:
            continue
        host = (parsed.hostname or "").lower()
        if same_host_only and base_host and host and host != base_host:
            continue
        if absolute not in structured:
            structured.append(absolute)
    return structured
