from attackcastle.adapters.web_probe.parser import (
    detect_cdn_parking_page,
    detect_admin_interface,
    detect_default_page,
    detect_generic_http_response,
    detect_login_portal,
    detect_redirect_loop,
    detect_soft_404,
    detect_waf_cdn,
    explain_technology_fingerprints,
)


def test_detect_login_portal_from_password_and_terms():
    detected, reasons = detect_login_portal(
        "<html><title>Sign In</title><input type='password' name='password'></html>",
        {},
        "https://portal.example.com/login",
        "Sign In",
        ["username", "password"],
    )
    assert detected is True
    assert reasons


def test_detect_admin_interface_and_default_page():
    admin_detected, _ = detect_admin_interface(
        "<html><title>Admin Console</title></html>",
        "https://portal.example.com/admin",
        "Admin Console",
    )
    default_detected, _ = detect_default_page(
        "<html><title>Welcome to nginx!</title></html>",
        "Welcome to nginx!",
        {"server": "nginx"},
    )
    assert admin_detected is True
    assert default_detected is True


def test_detect_soft_404_and_waf():
    assert detect_soft_404(200, "welcome to portal homepage", 200, "welcome to portal homepage") is True
    provider, confidence = detect_waf_cdn({"server": "cloudflare", "cf-ray": "123"})
    assert provider == "cloudflare"
    assert confidence > 0.0


def test_detect_generic_response_redirect_loop_and_parking_page():
    generic = detect_generic_http_response(
        403,
        "Access denied by cloudflare security check",
        "Access denied",
        [
            {
                "status_code": 403,
                "body_text": "Access denied by cloudflare security check",
                "title": "Access denied",
            }
        ],
    )
    loop, reasons = detect_redirect_loop(
        [
            {"from": "https://a.example.com", "to": "https://b.example.com", "status": 302},
            {"from": "https://b.example.com", "to": "https://a.example.com", "status": 302},
        ],
        "https://a.example.com",
    )
    provider, parking_reasons = detect_cdn_parking_page(
        {"server": "cloudfront"},
        "Error",
        "Generated by cloudfront",
        "https://cdn.example.com",
    )
    assert generic is not None
    assert generic["matched_canaries"] == 1
    assert loop is True
    assert reasons
    assert provider == "cloudfront"
    assert parking_reasons


def test_explain_technology_fingerprints_builds_version_tiers():
    inventory = explain_technology_fingerprints(
        {"server": "nginx/1.24.0", "x-generator": "WordPress 6.5.0"},
        "<html><head></head><body>wp-content</body></html>",
    )
    names = {item["name"]: item for item in inventory}
    assert "WordPress" in names
    assert names["WordPress"]["version_confidence_tier"] == "multi-source corroborated"
