from __future__ import annotations

import json
import sys

from attackcastle.core.models import RunData, RunMetadata, now_utc
from attackcastle.gui.extensions import CommandHookExtensionConfig, ExtensionManifest
from attackcastle.gui.extensions_runtime import run_command_hook_extensions
from attackcastle.gui.extensions import ExtensionRecord
from attackcastle.gui.models import GuiProfile, ScanRequest
from attackcastle.storage.run_store import RunStore


def test_command_hook_extensions_capture_report_payload_and_tool_execution(tmp_path) -> None:
    script_path = tmp_path / "emit_extension.py"
    script_path.write_text(
        "\n".join(
            [
                "import json",
                "import os",
                "from pathlib import Path",
                "payload = {",
                "  'status': 'completed',",
                "  'summary': 'Extension completed successfully.',",
                "  'facts': {'extra': 'value'},",
                "  'report': {",
                "    'title': 'Custom Output',",
                "    'cards': [{'label': 'Rows', 'value': '3'}],",
                "    'notes': ['Generated by test extension.']",
                "  }",
                "}",
                "Path(os.environ['AC_EXTENSION_OUTPUT_JSON']).write_text(json.dumps(payload), encoding='utf-8')",
            ]
        ),
        encoding="utf-8",
    )
    manifest = ExtensionManifest(
        schema_version="extensions/v1",
        extension_id="emit-extension",
        name="Emit Extension",
        version="1.0.0",
        capabilities=["command_hook"],
        command_hook=CommandHookExtensionConfig(
            command=sys.executable,
            args=[str(script_path)],
            timeout_seconds=30,
        ),
    )
    extension_dir = tmp_path / "extensions" / "emit-extension"
    extension_dir.mkdir(parents=True)
    record = ExtensionRecord(
        directory=extension_dir,
        manifest_path=extension_dir / "extension.json",
        manifest=manifest,
        raw_text=json.dumps(manifest.to_dict()),
    )
    request = ScanRequest(
        scan_name="GUI Scan",
        target_input="example.com",
        profile=GuiProfile(name="Standard"),
        output_directory=str(tmp_path),
        enabled_extension_ids=["emit-extension"],
    )
    run_store = RunStore(output_root=tmp_path, run_id="gui-ext")
    run_data = RunData(
        metadata=RunMetadata(
            run_id="gui-ext",
            target_input="example.com",
            profile="prototype",
            output_dir=str(run_store.run_dir),
            started_at=now_utc(),
        )
    )

    results = run_command_hook_extensions(
        request=request,
        records=[record],
        run_store=run_store,
        run_data=run_data,
    )

    assert len(results) == 1
    assert results[0]["extension_id"] == "emit-extension"
    assert results[0]["report"]["cards"][0]["value"] == "3"
    assert run_data.facts["gui.extensions"][0]["summary"] == "Extension completed successfully."
    assert run_data.tool_executions[0].tool_name == "extension:emit-extension"
